
[package]
name = "blusorter-tauri"
version = "0.1.0"
edition = "2021"


[dependencies]
sorter-core = { path = "../sorter-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"


tauri = { version = "2", features = [] }
